### ISSUE TITLE
error for feature colletion

### ISSUE THREAD

**Issue by gagan-bansal** [mapbox/geojson-extent#3]
My test data:
```javascript
var ext = require('geojson-extent'),
featColl ={"type":"FeatureCollection","features":[{"type":"Feature","properties":{"osm_id":243819778,"name":"Port Louis","type":"city","population":147688},"geometry":{"type":"Point","coordinates":[57.5045331,-20.1637281]}}]};
console.log(ext.bboxify(featColl));
```

and here is the output error:
```
/mypath/node_modules/geojson-extent/node_modules/geojson-coords/index.js:10
    normalized.features.forEach(function(feature) {
              ^
TypeError: Cannot read property 'features' of null
    at module.exports (/mypath/node_modules/geojson-extent/node_modules/geojson-coords/index.js:10:15)
    at getExtent (/mypath/node_modules/geojson-extent/index.js:25:18)
    at Object.<anonymous> (/mypath/node_modules/geojson-extent/index.js:16:26)
    at walker (/mypath/node_modules/geojson-extent/node_modules/traverse/index.js:190:22)
    at /mypath/node_modules/geojson-extent/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
    at forEach (/mypath/node_modules/geojson-extent/node_modules/traverse/index.js:298:31)
    at walker (/mypath/node_modules/geojson-extent/node_modules/traverse/index.js:203:13)
    at /mypath/node_modules/geojson-extent/node_modules/traverse/index.js:208:29
    at Array.forEach (native)
```

Or am I doing something wrong?

**Comment by tmcw** [comment]
This is a bug in geojson-extent; it's using the "type" property to guess what things are bbox'able, and since there's type in the properties object, it's trying to find its bbox. I'll need to do a less-lazy traversal of the object.
